[package]
name = "risc_zero"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
architecture_utils = { path = "../architecture_utils" }
clap = "2.33"
tui = "0.15"
termion = "1.5"
rand = "0.8.4"

