[package]
name = "architecture_utils"
version = "0.1.0"
authors = ["Gabriel Dertoni <gab.dertoni@gmail.com>", "Natan Sanches <natanhsanches@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
